url: https://y7kim.github.io

# Site settings
title: Lint Trap Records
email: info@linttraprecords.com
description: "MUSIC"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7CD51D
  secondary: ffaaff  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kevin Lint
  pic: kevinlint
  position: Singer/Songwriter and Producer
  social:
    - title: twitter
      url: http://twitter.com/kvnlnt
    - title: facebook
      url: http://facebook.com/kevinlintmusic
- name: Jaymie Charnette
  pic: jaymie
  position: Manager/Glue
  social:
    - title: facebook
      url: http://facebook.com/jjaymie

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/kvnlnt
  - title: facebook
    url: http://facebook.com/kevinlintmusic

# Postal address (add as many lines as necessary)
address:
  - line: Mukilteo Wa 98275

# Build settings
markdown: kramdown
permalink: pretty