url: https://y7kim.github.io

# Site settings
title: Lint Trap Records
email: info@linttraprecords.com
description: "MUSIC"

# Color settings (hex-codes without the leading hash-tag)
color:

  primary: 7CD51D
  secondary: ffaaff  
  secondary-dark: 333

# Team names, titles and social links
people:

- name: Kevin Lint
  pic: kevinlint
  track: 160910408
  position: Singer/Songwriter and Producer
  social:
    - title: twitter
      url: http://twitter.com/linttraprecords
    - title: facebook
      url: http://facebook.com/linttraprecords

- name: Jaymie Charnette
  pic: jaymie
  position: Manager/Glue
  social:
    - title: facebook
      url: http://facebook.com/jjaymie

# Album names, artists, etc
albums:

- name: Salt Water Hymns
  artist: Joe Sneva
  year: 2014
  track: 160910408
  tags: "Folk, Pop"

- name: The Sand Reckoner
  artist: Kevin Lint
  year: 2013
  track: 194840330
  tags: "Americana, Singer-Songwriter"

- name: An Echo
  artist: Joe Sneva
  year: 2012
  track: 194843489
  tags: "Acoustic, Folk, Pop"

- name: Story Problems
  artist: Kevin Lint
  year: 2008
  track: 194847350
  tags: "Americana Rock, Singer-Songwriter"

# - name: L.A. Is On Fire
#   artist: The Sweet Dominiques
#   year: 2012
#   track: "none"
#   tags: "Acoustic, Pop"

# - name: Record Store Rumble
#   artist: The Sweet Dominiques
#   year: 2011
#   track: "none"
#   tags: "Acoustic, Pop"

# - name: The Sweet Dominiques
#   artist: The Sweet Dominiques
#   year: 2010
#   track: "none"
#   tags: "Acoustic, Pop"

- name: "Skirts & Satellites"
  artist: Neon Sharks
  year: 2010
  track: 194861852
  tags: "Acoustic, Pop"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: twitter
    url: http://twitter.com/linttraprecords
  - title: facebook
    url: http://facebook.com/linttraprecords

# Postal address (add as many lines as necessary)
address:

  - line: Mukilteo Wa 98275

# Build settings
markdown: kramdown
permalink: pretty